// Color star entity - decorative stars with various shapes and behaviors
// Note: Health and money orbs (created from asteroid/enemy destruction) are collectible
import { GAME_CONFIG, NORMAL_STAR_COLORS, STAR_SHAPES } from '../constants.js';
import { random, wrap, glowSpriteCache } from '../utils.js';
import { frameClock } from '../frame-clock.js';

function isMobile() {
    return window.matchMedia && window.matchMedia('(hover: none) and (pointer: coarse), (max-width: 768px)').matches;
}

export class ColorStar {
    constructor() {
        this.width = window.innerWidth;
        this.height = window.innerHeight;
        this.active = false;
    }
    
    reset(x, y, starType = 'decorative', z, density) {
        this.x = x;
        this.y = y;
        this.z = z;
        this.density = density;
        
        // Star types: 'decorative', 'health', 'money' (health and money are orbs)
        this.starType = starType;
        this.isCollectible = (starType === 'health' || starType === 'money');
        
        let scale = isMobile() ? GAME_CONFIG.MOBILE_SCALE : 1;
        
        // Radius and twinkle speed are now affected by density
        const densityFactor = 0.7 + (this.density || 0.5) * 0.6;
        
        // 15% chance for a "big star" - much larger and brighter
        const isBigStar = Math.random() < 0.15;
        if (isBigStar) {
            this.radius = (this.z * 3.5 + 1.5) * scale * densityFactor; // Much bigger stars to show shapes
            this.isBigStar = true;
        } else {
            this.radius = (this.z * 1.2 + 0.6) * scale * densityFactor; // Larger normal stars too
            this.isBigStar = false;
        }
        
        this.opacity = 0;
        this.opacityOffset = Math.random() * Math.PI * 2;
        this.twinkleSpeed = random(0.003, 0.008) * (1 + this.z * 0.2) * densityFactor; // Much slower, more gentle
        
        // Shape selection — foreground stars (z >= 2.0) are always simple white
        // blinking points to avoid confusion with game entities
        if (this.z >= 2.0) {
            this.shape = 'point';
            this.isBigStar = false;
        } else if (isBigStar) {
            const interestingShapes = ['star4', 'star5', 'star6', 'star8', 'hexagon', 'diamond', 'triangle', 'sparkle', 'burst'];
            this.shape = Math.random() < 0.8 ?
                        interestingShapes[Math.floor(Math.random() * interestingShapes.length)] :
                        STAR_SHAPES[Math.floor(Math.random() * STAR_SHAPES.length)];
        } else {
            this.shape = STAR_SHAPES[Math.floor(Math.random() * STAR_SHAPES.length)];
        }
        
        this.points = Math.floor(random(4, 7)) * 2;
        this.innerRadiusRatio = random(0.4, 0.8);
        
        // Add rotation and size variation
        this.rotation = 0;
        this.rotationSpeed = random(-0.02, 0.02);
        
        // Big stars with interesting shapes get enhanced rotation - more subtle
        if (isBigStar && ['star5', 'star6', 'star8', 'sparkle'].includes(this.shape)) {
            this.rotationSpeed *= 1.3; // Gentle showcase of rotating complex shapes
        }
        // Big stars get larger size variation
        if (this.isBigStar) {
            this.sizeVariation = random(1.5, 2.8); // Big stars: 150% to 280% size variation - showcase shapes!
        } else {
            this.sizeVariation = random(0.9, 1.6); // Normal stars: 90% to 160% size variation
        }
        this.pulseSpeed = random(0.002, 0.006); // Slower, more gentle pulsing
        this.pulseOffset = Math.random() * Math.PI * 2;
        
        // Shape-specific enhancements for visual interest - toned down
        if (['star5', 'star6', 'star8'].includes(this.shape)) {
            this.rotationSpeed *= 1.2; // Slightly faster rotation, not too dramatic
        }
        if (['sparkle', 'burst'].includes(this.shape)) {
            this.pulseSpeed *= 1.5; // More subtle pulse enhancement
        }
        
        this.vel = { x: 0, y: 0 };
        this.active = true;
        
        if (this.isCollectible) {
            // Collectible orbs (health and money) are not generated by the noise field
            this.x = x || random(0, this.width);
            this.y = y || random(0, this.height);
            this.z = random(1.5, 3.0); // Close and bright
            this.density = 0.8;
            
            // Set colors and symbols based on orb type
            if (this.starType === 'health') {
                this.color = '#00ff7f'; // Green for health orbs
                this.borderColor = '#ffd700'; // Gold border
                // Health orbs use random star geometries like other orbs
                const healthStarShapes = ['star4', 'star5', 'star6', 'star8', 'burst', 'sparkle'];
                this.shape = healthStarShapes[Math.floor(Math.random() * healthStarShapes.length)];
                this.baseRadius = (this.z * 1.2 + 0.4) * scale * 1.8; // Store base radius for scaling
                this.radius = this.baseRadius; // Will be modified by size multiplier in game engine
            } else if (this.starType === 'money') {
                this.color = '#FFD700'; // Gold for money orbs
                this.borderColor = '#FFA500'; // Orange border
                this.shape = 'circle'; // Money orbs are circular with symbols
                // Add money symbol
                const symbols = ['$', '¥', '£', '€'];
                this.moneySymbol = symbols[Math.floor(Math.random() * symbols.length)];
                this.baseRadius = (this.z * 1.2 + 0.4) * scale * 3.2; // Store base radius for scaling
                this.radius = this.baseRadius; // Will be modified by size multiplier in game engine
            }

            // Initial velocity will be set by createOrbBurst for explosion effect
            this.vel = { x: 0, y: 0 };
            this.life = 1800;
        } else {
            // Decorative stars use normal colors
            this.color = NORMAL_STAR_COLORS[Math.floor(Math.random() * NORMAL_STAR_COLORS.length)];
            this.borderColor = NORMAL_STAR_COLORS[Math.floor(Math.random() * NORMAL_STAR_COLORS.length)];
            this.life = -1;
        }
        
        // Legacy support for old property - both health and money orbs should be attracted to player
        this.isBurst = (this.starType === 'health' || this.starType === 'money');
    }
    
    update(shipVel, playerPos, tractorEngaged, gameField = null) {
        if (!this.active) return;
        
        if (this.isBurst) {
            this.life--;
            if (this.life <= 0) {
                this.active = false;
                return;
            }
            
            this.vel.x *= GAME_CONFIG.ORB_FRIC;
            this.vel.y *= GAME_CONFIG.ORB_FRIC;
            this.x += this.vel.x;
            this.y += this.vel.y;
            
            this.opacity = Math.min(1, this.life / 120);
            
            // Home directly toward player
            const dx = playerPos.x - this.x;
            const dy = playerPos.y - this.y;
            const dist = Math.hypot(dx, dy);
            
            if (dist > 1) {
                // Strengthened base homing behavior - always moves towards player
                const baseAttraction = 0.8; // Much stronger constant homing
                this.vel.x += (dx / dist) * baseAttraction * 0.15 * this.z;
                this.vel.y += (dy / dist) * baseAttraction * 0.15 * this.z;
                
                // Strong attraction at medium range (within 100 pixels)
                if (dist < 100) {
                    const strongAttraction = 15; // Stronger pull when in medium range
                    const proximityMultiplier = (100 - dist) / 100; // Stronger as it gets closer
                    this.vel.x += (dx / dist) * strongAttraction * proximityMultiplier * this.z;
                    this.vel.y += (dy / dist) * strongAttraction * proximityMultiplier * this.z;
                }
                
                // Very strong magnetic pull at close range (within 40 pixels)
                if (dist < 40) {
                    const magneticAttraction = 25; // Very strong pull when very close
                    const magneticMultiplier = (40 - dist) / 40; // Maximum strength when touching
                    this.vel.x += (dx / dist) * magneticAttraction * magneticMultiplier * this.z;
                    this.vel.y += (dy / dist) * magneticAttraction * magneticMultiplier * this.z;
                }
                
                // Enhanced attraction when tractor beam is active (works at longer range)
                if (tractorEngaged) {
                    let tractorAttraction = GAME_CONFIG.ACTIVE_STAR_ATTR * 1500; // Increased tractor strength
                    let tractorDist = GAME_CONFIG.ACTIVE_STAR_ATTRACT_DIST;
                    
                    if (dist < tractorDist) {
                        const tractorForce = tractorAttraction * (1 - dist / tractorDist);
                        this.vel.x += (dx / dist) * tractorForce * this.z;
                        this.vel.y += (dy / dist) * tractorForce * this.z;
                    }
                }
            }
        } else {
            // Update twinkle based on sine wave - much more subtle variation
            this.opacity = 0.6 + 0.3 * (Math.sin(frameClock.now * this.twinkleSpeed + this.opacityOffset) + 1) / 2;
            
            // Rotate the star
            this.rotation += this.rotationSpeed;
            
            // Pulse size
            this.pulseOffset += this.pulseSpeed;
            
            // Non-orb stars are no longer attracted to player - they just exist for visual effect
            // Remove all tractor beam and attraction logic
        }
        
                    // Reduced parallax effect for less distraction
            // Distant stars move much slower, close stars move faster
            // But orbs don't have parallax - they're gameplay elements
            if (!this.isBurst) {
                const parallaxFactor = Math.pow(this.z, 1.8) * 0.12; // Reduced exponent and multiplier for gentler parallax
                this.x -= shipVel.x * parallaxFactor;
                this.y -= shipVel.y * parallaxFactor;
                
                // Use game field dimensions if available, otherwise fall back to screen dimensions
                const wrapWidth = gameField ? gameField.width : this.width;
                const wrapHeight = gameField ? gameField.height : this.height;
                wrap(this, wrapWidth, wrapHeight);
            }
    }
    
    draw(ctx) {
        if (!this.active) return;
        
        // Calculate final opacity for rendering
        this.depthOpacity = Math.min(1, 0.5 + Math.pow(this.z / 4, 1.2));
        this.finalOpacity = this.opacity * this.depthOpacity;
        
        // Complex stars always use direct rendering for special effects
        if (this.isBurst || this.shape === 'sparkle' || this.shape === 'burst') {
            this.drawDirect(ctx);
            return;
        }
        
        // Simple stars will be handled by depth batch renderer
        // No rendering here - just property preparation
    }
    
    drawDirect(ctx) {
        ctx.save();
        ctx.translate(this.x, this.y);
        
        // Apply rotation
        ctx.rotate(this.rotation);
        
        // Calculate dynamic radius with size variation and pulse
        const pulseMultiplier = 1 + Math.sin(this.pulseOffset) * 0.08; // Much more subtle pulsing
        const dynamicRadius = this.radius * this.sizeVariation * pulseMultiplier;
        
        // Adjust opacity based on depth - brighter overall
        ctx.globalAlpha = this.finalOpacity;
        
        // Remove glow effects - use direct rendering for better visibility
        
        if (this.shape === 'point') {
            const borderSize = 1;
            ctx.fillStyle = this.borderColor;
            ctx.fillRect(
                -dynamicRadius / 2 - borderSize,
                -dynamicRadius / 2 - borderSize,
                dynamicRadius + borderSize * 2,
                dynamicRadius + borderSize * 2
            );
            ctx.fillStyle = this.color;
            ctx.fillRect(-dynamicRadius / 2, -dynamicRadius / 2, dynamicRadius, dynamicRadius);
        } else if (this.starType !== 'money') {
            // Skip normal shape drawing for money orbs - they have custom rendering
            ctx.beginPath();
            
            switch (this.shape) {
                case 'diamond':
                    ctx.moveTo(0, -dynamicRadius);
                    ctx.lineTo(dynamicRadius * 0.7, 0);
                    ctx.lineTo(0, dynamicRadius);
                    ctx.lineTo(-dynamicRadius * 0.7, 0);
                    ctx.closePath();
                    break;
                    
                case 'triangle':
                    ctx.moveTo(0, -dynamicRadius);
                    ctx.lineTo(dynamicRadius * 0.8, dynamicRadius * 0.5);
                    ctx.lineTo(-dynamicRadius * 0.8, dynamicRadius * 0.5);
                    ctx.closePath();
                    break;
                    
                case 'hexagon':
                    for (let i = 0; i < 6; i++) {
                        const a = i * Math.PI / 3;
                        const x = Math.cos(a) * dynamicRadius;
                        const y = Math.sin(a) * dynamicRadius;
                        if (i === 0) ctx.moveTo(x, y);
                        else ctx.lineTo(x, y);
                    }
                    ctx.closePath();
                    break;
                    
                case 'circle':
                    ctx.arc(0, 0, dynamicRadius, 0, Math.PI * 2);
                    break;
                    
                case 'square':
                    ctx.rect(-dynamicRadius * 0.7, -dynamicRadius * 0.7, dynamicRadius * 1.4, dynamicRadius * 1.4);
                    break;
                    
                case 'plus':
                    ctx.moveTo(0, -dynamicRadius);
                    ctx.lineTo(0, dynamicRadius);
                    ctx.moveTo(-dynamicRadius, 0);
                    ctx.lineTo(dynamicRadius, 0);
                    break;
                    
                case 'x':
                    ctx.moveTo(-dynamicRadius, -dynamicRadius);
                    ctx.lineTo(dynamicRadius, dynamicRadius);
                    ctx.moveTo(dynamicRadius, -dynamicRadius);
                    ctx.lineTo(-dynamicRadius, dynamicRadius);
                    break;
                    
                case 'star4':
                    for (let i = 0; i < 8; i++) {
                        const a = i * Math.PI / 4;
                        const r = i % 2 === 0 ? dynamicRadius : dynamicRadius * 0.4;
                        if (i === 0) ctx.moveTo(Math.cos(a) * r, Math.sin(a) * r);
                        else ctx.lineTo(Math.cos(a) * r, Math.sin(a) * r);
                    }
                    ctx.closePath();
                    break;
                    
                case 'star5':
                    for (let i = 0; i < 10; i++) {
                        const a = i * Math.PI / 5;
                        const r = i % 2 === 0 ? dynamicRadius : dynamicRadius * 0.4;
                        if (i === 0) ctx.moveTo(Math.cos(a) * r, Math.sin(a) * r);
                        else ctx.lineTo(Math.cos(a) * r, Math.sin(a) * r);
                    }
                    ctx.closePath();
                    break;
                    
                case 'star6':
                    for (let i = 0; i < 12; i++) {
                        const a = i * Math.PI / 6;
                        const r = i % 2 === 0 ? dynamicRadius : dynamicRadius * 0.4;
                        if (i === 0) ctx.moveTo(Math.cos(a) * r, Math.sin(a) * r);
                        else ctx.lineTo(Math.cos(a) * r, Math.sin(a) * r);
                    }
                    ctx.closePath();
                    break;
                    
                case 'star8':
                    for (let i = 0; i < 16; i++) {
                        const a = i * Math.PI / 8;
                        const r = i % 2 === 0 ? dynamicRadius : dynamicRadius * this.innerRadiusRatio;
                        if (i === 0) ctx.moveTo(Math.cos(a) * r, Math.sin(a) * r);
                        else ctx.lineTo(Math.cos(a) * r, Math.sin(a) * r);
                    }
                    ctx.closePath();
                    break;
                    
                case 'sparkle':
                    // 8-pointed sparkle with varying lengths
                    for (let i = 0; i < 8; i++) {
                        const a = i * Math.PI / 4;
                        const length = (i % 2 === 0) ? dynamicRadius : dynamicRadius * 0.6;
                        ctx.moveTo(0, 0);
                        ctx.lineTo(Math.cos(a) * length, Math.sin(a) * length);
                    }
                    // Add central cross for sparkle effect
                    ctx.moveTo(-dynamicRadius * 0.3, 0);
                    ctx.lineTo(dynamicRadius * 0.3, 0);
                    ctx.moveTo(0, -dynamicRadius * 0.3);
                    ctx.lineTo(0, dynamicRadius * 0.3);
                    break;
                    
                case 'burst':
                    // Radiating lines of varying lengths - more dramatic
                    for (let i = 0; i < 16; i++) {
                        const a = i * Math.PI / 8;
                        const length = dynamicRadius * (0.4 + Math.sin(frameClock.now * 0.005 + i) * 0.3);
                        ctx.moveTo(0, 0);
                        ctx.lineTo(Math.cos(a) * length, Math.sin(a) * length);
                    }
                    break;
                    
                case 'circle':
                    // For money orbs and other circular shapes, draw a filled circle
                    ctx.arc(0, 0, dynamicRadius, 0, 2 * Math.PI);
                    break;
                    
                default:
                    // Default X shape
                    ctx.moveTo(-dynamicRadius, -dynamicRadius);
                    ctx.lineTo(dynamicRadius, dynamicRadius);
                    ctx.moveTo(dynamicRadius, -dynamicRadius);
                    ctx.lineTo(-dynamicRadius, dynamicRadius);
                    break;
            }
            
            // Enhanced border for shape definition
            ctx.strokeStyle = this.borderColor;
            ctx.lineWidth = this.isBigStar ? 3 : 2;
            ctx.stroke();
            
            // Main shape stroke - thicker to showcase intricate shapes
            ctx.strokeStyle = this.color;
            ctx.lineWidth = (this.isBigStar ? 4 : 2.5) + this.z / 2; // Much thicker lines
            ctx.stroke();
            
            // Add subtle fill for complex shapes to make them more visible
            if (['star4', 'star5', 'star6', 'star8', 'hexagon', 'diamond', 'triangle'].includes(this.shape)) {
                ctx.save();
                ctx.globalAlpha = this.finalOpacity * 0.3; // Subtle fill
                ctx.fillStyle = this.color;
                ctx.fill();
                ctx.restore();
            }
            
            // Special fill for money orbs - make them more subtle to highlight the symbol
            if (this.starType === 'money' && this.shape === 'circle') {
                ctx.save();
                ctx.globalAlpha = this.finalOpacity * 0.2; // Very subtle fill for money orbs
                ctx.fillStyle = this.color;
                ctx.fill();
                ctx.restore();
            }
        }
        
        // Add extra visibility for big stars - enhanced center glow
        // OPT-2: use pre-rendered glow sprite instead of live ctx.shadowBlur
        if (this.isBigStar) {
            ctx.save();
            const glowR = dynamicRadius * 0.3;
            glowSpriteCache.draw(ctx, 0, 0, this.color, glowR, 8, this.finalOpacity * 0.6);

            // Add sparkle effect for the most interesting shapes (no shadowBlur needed)
            if (['star5', 'star6', 'star8', 'sparkle', 'burst'].includes(this.shape)) {
                ctx.globalAlpha = this.finalOpacity * 0.4;
                ctx.strokeStyle = '#ffffff';
                ctx.lineWidth = 1;
                ctx.beginPath();
                for (let i = 0; i < 8; i++) {
                    const angle = (i / 8) * Math.PI * 2;
                    const innerR = dynamicRadius * 0.7;
                    const outerR = dynamicRadius * 1.1;
                    ctx.moveTo(Math.cos(angle) * innerR, Math.sin(angle) * innerR);
                    ctx.lineTo(Math.cos(angle) * outerR, Math.sin(angle) * outerR);
                }
                ctx.stroke();
            }

            ctx.restore();
        }
        
        // Special glow effect for collectible orbs to indicate they're collectible (skip for money orbs)
        // OPT-2: use pre-rendered glow sprite for inner core; plain stroke for collection ring
        if ((this.isBurst || this.isCollectible) && this.starType !== 'money') {
            ctx.save();

            const pulseIntensity = 0.3 + 0.4 * Math.sin(frameClock.now * 0.008 + this.x * 0.01);

            // Collection area indicator - plain stroke (no shadowBlur needed, ring is visible)
            ctx.globalAlpha = this.finalOpacity * pulseIntensity * 0.3;
            ctx.strokeStyle = this.color;
            ctx.lineWidth = 2;
            ctx.beginPath();
            ctx.arc(0, 0, dynamicRadius + 15, 0, 2 * Math.PI);
            ctx.stroke();

            // Inner bright core via pre-rendered glow sprite
            glowSpriteCache.draw(ctx, 0, 0, this.color, dynamicRadius * 0.6, 8, this.finalOpacity * 0.9);

            ctx.restore();
        }
        
        // Custom rendering for money orbs - optimized for gameplay visibility
        if (this.starType === 'money' && this.moneySymbol) {
            ctx.save();
            
            // Pulsing effect for the circle
            const pulseIntensity = 0.5 + 0.4 * Math.sin(frameClock.now * 0.01 + this.x * 0.01);
            const circleRadius = dynamicRadius * (0.9 + pulseIntensity * 0.2);
            
            // Draw pulsating gold circle - more visible
            ctx.globalAlpha = this.finalOpacity * pulseIntensity * 0.8;
            ctx.strokeStyle = '#FFD700';
            ctx.lineWidth = 3;
            ctx.beginPath();
            ctx.arc(0, 0, circleRadius, 0, 2 * Math.PI);
            ctx.stroke();
            
            // Draw inner glow circle
            ctx.globalAlpha = this.finalOpacity * pulseIntensity * 0.4;
            ctx.strokeStyle = '#FFFF88';
            ctx.lineWidth = 2;
            ctx.beginPath();
            ctx.arc(0, 0, circleRadius * 0.6, 0, 2 * Math.PI);
            ctx.stroke();
            
            // Draw semi-transparent dark background for symbol contrast
            ctx.globalAlpha = this.finalOpacity * 0.7;
            ctx.fillStyle = 'rgba(0, 0, 0, 0.6)';
            ctx.beginPath();
            ctx.arc(0, 0, dynamicRadius * 0.7, 0, 2 * Math.PI);
            ctx.fill();
            
            // Reset for symbol drawing
            ctx.globalAlpha = 1.0;
            ctx.shadowColor = 'transparent';
            ctx.shadowBlur = 0;
            
            // Draw the money symbol - large and highly visible
            const fontSize = Math.max(16, Math.floor(dynamicRadius * 1.2));
            ctx.font = `${fontSize}px "Fira Code", "Consolas", "Courier New", monospace`;
            ctx.textAlign = 'center';
            ctx.textBaseline = 'middle';
            
            // Draw thin white outline for contrast
            ctx.strokeStyle = '#FFFFFF';
            ctx.lineWidth = 1;
            ctx.strokeText(this.moneySymbol, 0, 0);
            
            // Draw bright golden symbol (single draw call)
            ctx.fillStyle = '#FFD700';
            ctx.shadowColor = '#FFD700';
            ctx.shadowBlur = 2;
            ctx.fillText(this.moneySymbol, 0, 0);
            
            ctx.restore();
        }
        
        ctx.restore();
    }
    
    // Direct rendering fallback for simple shapes (used when batching is disabled or as fallback)
    drawDirectSimple(ctx) {
        if (!this.active) return;
        
        ctx.save();
        ctx.translate(this.x, this.y);
        
        // Apply rotation
        ctx.rotate(this.rotation);
        
        // Calculate dynamic radius with size variation and pulse
        const pulseMultiplier = 1 + Math.sin(this.pulseOffset) * 0.1;
        const dynamicRadius = this.radius * this.sizeVariation * pulseMultiplier;
        
        // Use stored opacity
        ctx.globalAlpha = this.finalOpacity;
        
        if (this.shape === 'point') {
            const borderSize = 1;
            ctx.fillStyle = this.borderColor;
            ctx.fillRect(
                -dynamicRadius / 2 - borderSize,
                -dynamicRadius / 2 - borderSize,
                dynamicRadius + borderSize * 2,
                dynamicRadius + borderSize * 2
            );
            ctx.fillStyle = this.color;
            ctx.fillRect(-dynamicRadius / 2, -dynamicRadius / 2, dynamicRadius, dynamicRadius);
        } else if (this.shape === 'circle') {
            ctx.fillStyle = this.color;
            ctx.beginPath();
            ctx.arc(0, 0, dynamicRadius, 0, 2 * Math.PI);
            ctx.fill();
        } else {
            // Simple stroke rendering for other shapes
            ctx.strokeStyle = this.color;
            ctx.lineWidth = 1.5 + this.z / 3;
            ctx.beginPath();
            
            switch (this.shape) {
                case 'diamond':
                    ctx.moveTo(0, -dynamicRadius);
                    ctx.lineTo(dynamicRadius * 0.7, 0);
                    ctx.lineTo(0, dynamicRadius);
                    ctx.lineTo(-dynamicRadius * 0.7, 0);
                    ctx.closePath();
                    break;
                case 'triangle':
                    ctx.moveTo(0, -dynamicRadius);
                    ctx.lineTo(dynamicRadius * 0.8, dynamicRadius * 0.5);
                    ctx.lineTo(-dynamicRadius * 0.8, dynamicRadius * 0.5);
                    ctx.closePath();
                    break;
                case 'plus':
                    ctx.moveTo(0, -dynamicRadius);
                    ctx.lineTo(0, dynamicRadius);
                    ctx.moveTo(-dynamicRadius, 0);
                    ctx.lineTo(dynamicRadius, 0);
                    break;
                case 'x':
                    ctx.moveTo(-dynamicRadius, -dynamicRadius);
                    ctx.lineTo(dynamicRadius, dynamicRadius);
                    ctx.moveTo(dynamicRadius, -dynamicRadius);
                    ctx.lineTo(-dynamicRadius, dynamicRadius);
                    break;
                default:
                    // Default to circle
                    ctx.arc(0, 0, dynamicRadius, 0, 2 * Math.PI);
                    break;
            }
            
            ctx.stroke();
        }
        
        ctx.restore();
    }
} 